### ISSUE TITLE
-fipa-pta is universally broken in all GCC versions after 5.5.0 and should be disabled

### ISSUE THREAD

**Issue by Muffindrake** [InBetweenNames/gentooLTO#257] opened 2019-03-12 09:54 UTC
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88936

The bug remains `ASSIGNED` despite claims in one of the current PRs to this repository that `GCC 8.3.0 contained fixes`, despite no explicit mention of this bug in the 8.3.0 changelog.

**Comment by InBetweenNames** [comment] 2019-03-12 13:33
Wow, great find!  I've disabled `-fipa-pta` globally in this repo until this gets resolved.  Anyone using a supported configuration should receive the update to their `CFLAGS` when they next `emerge --sync`.  Hopefully this will be resolved in the next major GCC release.  I may post an eselect news at some point advising anyone using this flag to do a full system rebuild.

**Comment by ionenwks** [comment] 2019-03-13 23:23
I'm not surprised to see this confirmed. Had a lot of strange issues with it myself and had stopped using it pretty early rather than setting exceptions, often the problems weren't segfaults but strange behavior that were hard to diagnose later on (never safe to mess with that but I tried to build glibc with it once anyway, and then tried to rebuild gcc and it started giving errors with includes that felt completely unrelated)

**Comment by barolo** [comment] 2019-03-14 12:17
I've been using -fipa-pta on world since forever and had no issues whatsoever. I'm on AMD, is it confined to Intel only?

**Comment by gcs-github** [comment] 2019-03-14 12:33
Well, the problem is that `-fipa-pta` generates invalid code in specific situations. There's no guarantee that you would hit these cases at runtime, which can explain why you didn't notice any issue. I haven't had issues with the flag either (excepted maybe as properly handled by the LTO workarounds from this overlay) but the threat of invalid code generation is scary enough to warrant avoiding the flag by default.

This isn't specific to Intel, and an example of the problem with a reproducer is given in the GCC bug tracker link posted in this issue.

**Comment by InBetweenNames** [comment] 2019-03-16 03:32
Better to stay safe than sorry for sure.  I'll re-enable this once it's fixed upstream.

**Comment by justanerd** [comment] 2019-04-15 11:24
Now fixed in trunk:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88936

**Comment by InBetweenNames** [comment] 2019-05-03 17:35
GCC 9.1.0 is now live and GentooLTO now supports it.  I'm leaving `-fipa-pta` out of the defaults for a few weeks while everyone upgrades.  However, interested users can opt in manually in their `CFLAGS`.  Leaving this issue open until it is re-added, in case problems arise.

**Comment by InBetweenNames** [comment] 2019-06-27 04:14
OK -- no major hurdles from `-fipa-pta`, so closing this issue.  If it needs to be reopened, just comment.

**Closed by InBetweenNames** 2019-06-27 04:14 UTC
