### ISSUE TITLE
Automatically assigning NTHREADS ?

### ISSUE THREAD

**Issue by jonesmz** [InBetweenNames/gentooLTO#527] opened 2020-05-20 19:22 UTC
I use the same /etc/portage on all of my machines (Stored in a git repository).

I want to have NTHREADS calculated based on how many cores are on a machine, but can't with the current method of things, as far as I'm able to tell.

Is this possible?

**Comment by wolfwood** [comment] 2020-05-20 19:46
I agree it would be best if it can be supported, but failing that, you could source a local conf file and do your per machine, non-git committed changes there.

it really depends on if whatever is interpreting make.conf supports bash's $() syntax.

**Comment by jonesmz** [comment] 2020-05-20 19:49
I do have a make.local file that i source at the end of make.conf

However, by the time make.local is sourced, the associated changes to CFLAGS would have already been calculated.

There are other work-arounds, but none that are straight forward and don't require a lot of careful config file wrangling on my part.

**Comment by wolfwood** [comment] 2020-05-20 19:54
i think if you do ${NTHREADS} instead of $NTHREADS the substitution is lazy so late definition should be OK.

It seems NTHREADS="$(grep -c processor /proc/cpuinfo)" is not supported.

**Comment by jonesmz** [comment] 2020-05-20 19:59
I was not aware that Bash has any concept of lazy string substitution...?

Do you happen to know of documentation about that, or about Portage's usage of it?

**Comment by wolfwood** [comment] 2020-05-20 20:09
a) looks like I'm wrong about that

b) it might not be bash, I think its python pretending to be bash :(

closest thing to docs I've seen is `man portage`

it looks like you can fix your ordering issue by setting NTHREADS in /etc/env.d/99nthreads and then running env-update. when I did this I got -flto=$(grep -c processor /etc/cpuinfo) in my `emerge --info`, lol. so it doesn't do the substitution either, but it might kinda almost work?

**Comment by wolfwood** [comment] 2020-05-20 20:15
relevant?
https://forums.gentoo.org/viewtopic-t-882085.html?sid=e80046eda70aaf9dbc165f4b29dc9958

**Comment by jonesmz** [comment] 2020-05-20 20:18
Hrmm,

the suggestion for /etc/env.d/99nthreads would definitely do the trick.

If there's no other solution, i'll use that. Thanks for the suggestion!

**Comment by InBetweenNames** [comment] 2020-05-20 22:15
Actually, GCC 10 may be able to do this for you with `-flto=auto`.  Could you try that and let me know how it works for you?

**Comment by InBetweenNames** [comment] 2020-05-20 22:17
From the [GCC Docs](https://gcc.gnu.org/onlinedocs/gcc-10.1.0/gcc/Optimize-Options.html#Optimize-Options):

~~~
Use -flto=auto to use GNU make’s job server, if available, or otherwise fall back to autodetection of the number of CPU threads present in your system. 
~~~

**Comment by jonesmz** [comment] 2020-05-20 22:19
I will try this and report back to you when GCC 10 is stabilized by Gentoo.

Great suggestion.

**Comment by elsandosgrande** [comment] 2020-05-21 00:22
If `FLTO` were defined as `FLTO="-flto=${NTHREADS}"` and `NTHREADS` were defined in `make.conf` before sourcing `make.conf.lto` in `make.conf`, then there would be no issues.

Since `FLTO` is just `-flto`, I just add `-flto` to my `make.conf` and to the nested string business there.

**Comment by imrebuild** [comment] 2020-05-23 23:30
I can confirm that `NTHREADS="auto"` works on GCC 10.1. But `NTHREADS="${nproc}"` will get `error: missing argument to '-flto='`.

**Comment by dblaber** [comment] 2020-07-31 17:26
FYI, I confirmed this worked for me (before I saw this issue existed). I created a PR that just added some suggestions to use it https://github.com/InBetweenNames/gentooLTO/pull/564

**Closed** 2020-08-04 18:24 UTC
