### ISSUE TITLE
x11-libs/wxGTK fails to compile

### ISSUE THREAD

**Issue by flgw** [InBetweenNames/gentooLTO#40] opened 2017-10-13 16:51 UTC
Removing lto doesn't help here. Partial build.log:
```
/var/tmp/portage/x11-libs/wxGTK-3.0.3.1-r301/work/wxWidgets-3.0.3.1-abi_x86_64.amd64/bk-make-pch ./.pch/wxprec_xmldll/wx/wxprec.h.gch wx/wxprec.h x86_64-pc-linux-gnu-g++ -I./.pch/wxprec_xmldll -D__WX__      -DWXBUILDING      -I/var/tmp/portage/x11-libs/wxGTK-3.0.3.1-r301/work/wxWidgets-3.0.3.1/src/regex  -DwxUSE_GUI=0 -DWXUSINGDLL -DWXMAKINGDLL_XML -fPIC -DPIC -Wall -Wundef -Wunused-parameter -Wno-ctor-dtor-privacy -Woverloaded-virtual -D_FILE_OFFSET_BITS=64 -I/var/tmp/portage/x11-libs/wxGTK-3.0.3.1-r301/work/wxWidgets-3.0.3.1-abi_x86_64.amd64/lib/wx/include/base-unicode-3.0-gtk3 -I/var/tmp/portage/x11-libs/wxGTK-3.0.3.1-r301/work/wxWidgets-3.0.3.1/include -DWX_PRECOMP -pthread -O2 -pipe -march=native -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=both -fvisibility=hidden -fvisibility-inlines-hidden
rm -f /var/tmp/portage/x11-libs/wxGTK-3.0.3.1-r301/work/wxWidgets-3.0.3.1-abi_x86_64.amd64/lib/libwxregexu-3.0-gtk3.a
gcc-ar rc /var/tmp/portage/x11-libs/wxGTK-3.0.3.1-r301/work/wxWidgets-3.0.3.1-abi_x86_64.amd64/lib/libwxregexu-3.0-gtk3.a wxregex_regcomp.o wxregex_regexec.o wxregex_regerror.o wxregex_regfree.o
gcc-ranlib /var/tmp/portage/x11-libs/wxGTK-3.0.3.1-r301/work/wxWidgets-3.0.3.1-abi_x86_64.amd64/lib/libwxregexu-3.0-gtk3.a
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/crt1.o:function _start: error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:15845: .pch/wxprec_xmldll/wx/wxprec.h.gch] Error 1
make: *** Waiting for unfinished jobs....
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/crt1.o:function _start: error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:15549: .pch/wxprec_basedll/wx/wxprec.h.gch] Error 1
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../lib64/crt1.o:function _start: error: undefined reference to 'main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:15586: .pch/wxprec_netdll/wx/wxprec.h.gch] Error 1
 * ERROR: x11-libs/wxGTK-3.0.3.1-r301::THG failed (compile phase):
 *   emake failed
```

**Comment by pchome** [comment] 2017-10-13 18:13
x11-libs/wxGTK-**3.0.3.1-r301::THG**

**Comment by flgw** [comment] 2017-10-13 22:00
x11-libs/wxGTK-3.0.2.0-r301::gentoo:
[build.log](https://github.com/InBetweenNames/gentooLTO/files/1384115/build.log)

**Comment by InBetweenNames** [comment] 2017-10-14 15:05
Yup, I can reproduce this.  Investigating.

**Comment by InBetweenNames** [comment] 2017-10-14 15:37
It looks like this package may not fully respect LDFLAGS.  I was able to get it to build with:

~~~
x11-libs/wxGTK *FLAGS-="-Wl,--as-needed" *FLAGS-="-Wl,--hash-style=gnu"
~~~

@flgw could you try this?

**Comment by pchome** [comment] 2017-10-14 15:45
https://bugs.gentoo.org/504204 ?

**Comment by InBetweenNames** [comment] 2017-10-14 15:46
Definitely related to that bug.  It seems the ebuild itself should be patched for this one.

**Comment by pchome** [comment] 2017-10-14 15:47
>> P.S. In my case those flags were introduced into CXXFLAGS by portage-bashrc-mv


😄

**Comment by InBetweenNames** [comment] 2017-10-14 15:52
Heheh yeah, actually if you check your Portage profile, it will likely have as your default `LDFLAGS`:

~~~
>cat /usr/portage/profiles/default/linux/make.defaults | grep LDFLAGS
# Adding LDFLAGS="-Wl,-O1 for all Linux profiles by default
# direction with how LDFLAGS will be set by default, this entry
# Note that adding LDFLAGS="-Wl,-O1 ${LDFLAGS}" breaks dev-util/boost-build
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
~~~

So really, this should affect more people!  Most likely people just override LDFLAGS like this though:

~~~
LDFLAGS=...
~~~
instead of
~~~
LDFLAGS="${LDFLAGS} ..."
~~~

which wipes the default settings.

**Comment by pchome** [comment] 2017-10-14 15:53
`$ cat /var/db/pkg/x11-libs/wxGTK-3.0.2.0-r3/LDFLAGS `
```
-Wl,--hash-style=gnu -march=native -O3 -fgraphite-identity -ftree-loop-distribution -floop-nest-optimize -flto=3 -fuse-linker-plugin -pipe
```
not using bashrc and no build problem

**Comment by InBetweenNames** [comment] 2017-10-14 16:03
Really?  On mine I get the `main` error if I leave `-Wl,--hash-style=gnu` in.  It must be specifically a problem that only manifests if linker flags are passed to the compiler through `-Wl` through `C*FLAGS`.  That is indeed something that `portage-bashrc-mv` does, since it combines all your `LDFLAGS` into your `C*FLAGS` (and vice versa) for LTO.

There is actually a way to control that behaviour with `NOLDADD`:

~~~
x11-libs/wxGTK NOLDADD=1
~~~

Documentation available here:
https://github.com/vaeth/portage-bashrc-mv/blob/master/bashrc.d/README

I'd still consider it a package bug, but this solution should be better than the previous one I mentioned since it accounts for all LDFLAGS like that.

**Comment by InBetweenNames** [comment] 2017-10-19 14:46
@flgw I've committed a workaround on HEAD for this.  Let me know if this solved the problem for you.

**Comment by InBetweenNames** [comment] 2018-05-03 18:47
As I have not heard from anyone about this and everything works on GCC 8.1.0, I'm going to close this issue. If problems persist, contact me and I'll reopen.

**Closed by InBetweenNames** 2018-05-03 18:47 UTC

**Comment by jelinekto** [comment] 2019-07-14 21:32
>  It must be specifically a problem that only manifests if linker flags are passed to the compiler through -Wl through C*FLAGS.

This issue is still present.

Now, the workaround currently in place does not suffice in my case since I set all the flags under `CFLAGS` and then do `LDFLAGS="${CFLAGS}"` (so I basically do manually what `portage-bashrc-mv` does automatically).

Adding `C*FLAGS-="-Wl,*"` covers this case.
