### ISSUE TITLE
x11-libs/cairo-1.16.0-r2::gentoo failed (compile phase)

### ISSUE THREAD

**Issue by ThGravo** [InBetweenNames/gentooLTO#187] opened 2018-11-15 09:12 UTC
```
make[5]: Leaving directory '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/boilerplate'
/bin/sh ../../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc -D_REENTRANT      -I/usr/include/pixman-1    -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/freetype2   -I/usr/include/libdrm -I/usr/include/libdrm -I/usr/include/libpng16       -Wall -Wextra -Wmissing-declarations -Werror-implicit-function-declaration -Wpointer-arith -Wwrite-strings -Wsign-compare -Wpacked -Wswitch-enum -Wmissing-format-attribute -Wvolatile-register-var -Wstrict-aliasing=2 -Winit-self -Wunsafe-loop-optimizations -Wno-missing-field-initializers -Wno-unused-parameter -Wno-attributes -Wno-long-long -Winline -fno-strict-aliasing -fno-common -Wno-unused-but-set-variable                          -D_REENTRANT  -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -g -O2   -o cairo-sphinx cairo_sphinx-sphinx.o -lpthread ../../util/cairo-script/libcairo-script-interpreter.la ../../boilerplate/libcairoboilerplate.la ../../src/libcairo.la -lglib-2.0  -lrt -lrt  -lm
libtool: link: x86_64-pc-linux-gnu-gcc -D_REENTRANT -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libdrm -I/usr/include/libpng16 -Wall -Wextra -Wmissing-declarations -Werror-implicit-function-declaration -Wpointer-arith -Wwrite-strings -Wsign-compare -Wpacked -Wswitch-enum -Wmissing-format-attribute -Wvolatile-register-var -Wstrict-aliasing=2 -Winit-self -Wunsafe-loop-optimizations -Wno-missing-field-initializers -Wno-unused-parameter -Wno-attributes -Wno-long-long -Winline -fno-strict-aliasing -fno-common -Wno-unused-but-set-variable -D_REENTRANT -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -g -O2 -o .libs/cairo-sphinx cairo_sphinx-sphinx.o  ../../util/cairo-script/.libs/libcairo-script-interpreter.so -llzo2 ../../boilerplate/.libs/libcairoboilerplate.a /var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so ../../src/.libs/libcairo.so -lpthread -lpixman-1 -lfontconfig -lfreetype -lEGL -ldl -lpng16 -lxcb-shm -lxcb -lxcb-render -lXrender -lX11 -lXext -lz -lGL -lglib-2.0 -lrt -lm
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glTexParameteri'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glScissor'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glEnable'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glDrawArrays'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glDrawElements'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glActiveTexture'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glBindTexture'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glBlendFuncSeparate'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glBlendFunc'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glGetError'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glDisable'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glDepthMask'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glClearStencil'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glClear'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glStencilOp'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glStencilFunc'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glColorMask'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glClearColor'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glDrawBuffer'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glReadBuffer'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glGetIntegerv'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glIsEnabled'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glViewport'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glGenTextures'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glTexImage2D'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glDeleteTextures'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glPixelStorei'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glReadPixels'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glTexSubImage2D'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glXMakeCurrent'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glXSwapBuffers'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glXGetCurrentDrawable'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glXGetCurrentContext'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glXQueryContext'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glXChooseFBConfig'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glXGetVisualFromFBConfig'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glXGetProcAddress'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/src/.libs/libcairo.so: error: undefined reference to 'glXQueryExtensionsString'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-egl.c:173: error: undefined reference to 'glFinish'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-glx.c:371: error: undefined reference to 'glGetString'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-glx.c:372: error: undefined reference to 'glGetString'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-glx.c:373: error: undefined reference to 'glGetString'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-glx.c:60: error: undefined reference to 'glXDestroyContext'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-glx.c:123: error: undefined reference to 'glXChooseVisual'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-glx.c:132: error: undefined reference to 'glXCreateContext'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-glx.c:121: error: undefined reference to 'glXChooseVisual'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-glx.c:356: error: undefined reference to 'glFinish'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-glx.c:184: error: undefined reference to 'glXChooseVisual'
/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0/boilerplate/cairo-boilerplate-glx.c:205: error: undefined reference to 'glXCreateContext'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:604: cairo-sphinx] Error 1
make[4]: Leaving directory '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/util/cairo-sphinx'
make[3]: *** [Makefile:1002: all-recursive] Error 1
make[3]: Leaving directory '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/util'
make[2]: *** [Makefile:779: all] Error 2
make[2]: Leaving directory '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64/util'
make[1]: *** [Makefile:908: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64'
make: *** [Makefile:759: all] Error 2
 * ERROR: x11-libs/cairo-1.16.0-r2::gentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=x11-libs/cairo-1.16.0-r2::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=x11-libs/cairo-1.16.0-r2::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/temp/environment'.
 * Working directory: '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64'
 * S: '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0'

 * Messages for package x11-libs/cairo-1.16.0-r2:

 * ERROR: x11-libs/cairo-1.16.0-r2::gentoo failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=x11-libs/cairo-1.16.0-r2::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=x11-libs/cairo-1.16.0-r2::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/temp/environment'.
 * Working directory: '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0-abi_x86_64.amd64'
 * S: '/var/tmp/portage/x11-libs/cairo-1.16.0-r2/work/cairo-1.16.0'
```

**Comment by InBetweenNames** [comment] 2018-11-15 23:42
Yes, this package works fine for me.

**Comment by ionenwks** [comment] 2018-11-16 06:36
Gave it a quick try and can't reproduce either, tried both with and without the opengl USE flag.

**Comment by InBetweenNames** [comment] 2018-12-14 20:20
Closing as I have not been able to reproduce the issue.  Please comment if the issue is still persisting.

**Closed by InBetweenNames** 2018-12-14 20:20 UTC
