### ISSUE TITLE
dev-libs/isl-0.21 builds with -flto but fails with -flto=${NTHREADS}

### ISSUE THREAD

**Issue by jelinekto** [InBetweenNames/gentooLTO#264] opened 2019-03-28 00:04 UTC
I'm guessing this is the important bit.
`cc: error trying to exec '/usr/libexec/gcc/x86_64-pc-linux-gnu/8.3.0/collect2': execv: Argument list too long`

[emerge-info.txt](https://github.com/InBetweenNames/gentooLTO/files/3015701/emerge-info.txt)
[build.log](https://github.com/InBetweenNames/gentooLTO/files/3015711/build.log)

**Comment by gcs-github** [comment] 2019-03-28 01:12
This looks like a limits problem. Do you have any non-default settings in /etc/security/limits.conf by any chance? Or something that would normally impact the default output or `ulimit -s`?
Can you CTRL+Z to stop emerge in the middle of the compilation, then run `ps aux` to find one of the compilation process IDs (make or gcc for example), and tell us what the output of `/proc/<pid_of_that_process>/limits` is?

**Comment by ellisonpatterson** [comment] 2019-03-28 16:31
Same issue.
ulimit -s
`8192`
limits.conf is unmodified.

**Comment by gcs-github** [comment] 2019-03-28 19:58
I'm reproducing. isl-0.20 compiled fine. 0.21 fails with the error mentioned in this issue. The diff between the two versions is 80k lines, so I'm not yet sure what's causing this exactly. I'm now suspecting a change in the package's build system.

**Comment by gcs-github** [comment] 2019-03-28 20:17
A `package.cflags` workaround:

```
dev-libs/isl /-flto=*/-flto=1
```

This will only slow down the compilation. The performance of the isl lib shouldn't be impacted.

**Comment by gcs-github** [comment] 2019-03-30 16:44
Turns out gentoo upstream has now masked isl-0.21 for this exact problem. For anyone using the workaround above, I think it's safe to add `=dev-libs/isl-0.21` to your local package.unmask

See: https://bugs.gentoo.org/682018

**Comment by InBetweenNames** [comment] 2019-04-01 15:36
Confirmed -- thanks @gcs-github for the report and for the workaround.  The PR has been merged.

**Closed by InBetweenNames** 2019-04-01 15:36 UTC

**Comment by ionenwks** [comment] 2019-04-06 16:23
I haven't tried yet but seems this particular problem has been sorted by gentoo with a gcc patch.

https://bugs.gentoo.org/682018

**Comment by gcs-github** [comment] 2019-04-06 17:34
Yep. That was fast :)

**Comment by gcs-github** [comment] 2019-04-06 21:36
For some reason, the package is still masked in upstream Gentoo, but I can confirm that the problem is gone on my end.

**Comment by ionenwks** [comment] 2019-04-06 22:24
It got unmasked just now, just needed some time.

**Comment by InBetweenNames** [comment] 2019-04-08 16:23
Excellent, I will commit the revert then.  Thanks for the followup!
