### ISSUE TITLE
app-admin/keepassxc-2.2.2 requires -fPIC to compile

### ISSUE THREAD

**Issue by soredake** [InBetweenNames/gentooLTO#58] opened 2017-10-25 15:36 UTC
`
/usr/lib/gcc/x86_64-pc-linux-gnu/7.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: /var/tmp/portage/app-admin/keepassxc-2.2.2/temp/ccERKDVM.ltrans0.ltrans.o: requires dynamic R_X86_64_PC32 reloc against '_ZN16AutoTypeExecutor9execDelayEP13AutoTypeDelay' which may overflow at runtime; recompile with -fPIC
`

`app-admin/keepassxc *FLAGS+=-fPIC` fixes build. I do not know if this is due to gentooLTO, can someone test?
UPD: seems gentooLTO is not related https://bugs.gentoo.org/buglist.cgi?quicksearch=fPIC&list_id=3710774

**Comment by InBetweenNames** [comment] 2017-10-25 22:57
Hi @soredake , thanks for the heads up on this.  As much as I'd like to include a workaround for this in this repo, unfortunately I have to keep things focused around the LTO goal, and this definitely non-LTO related.  I'm going to have to close the issue for now, but if you find later that LTO does indeed affect this, I will for sure reopen it.  Thanks!

**Comment by huglovefan** [comment] 2018-06-02 13:27
>if you find later that LTO does indeed affect this, I will for sure reopen it.

i ran into the same problem and found that if you enable the `autotype` use flag for keepassxc, you need to use either `*FLAGS+=-fPIC` or `*FLAGS-=-flto*` or the build will fail [(log)](https://u.lewd.se/NyvYt4_keepass-autotype-defaults.log)

i don't use any other use flags so i don't know what cflags they work with (but compiling without autotype works with the default lto flags)

is it lto-related enough? i could build the same version (2.2.4) fine with safe cflags before i started using gentooLTO

> UPD: seems gentooLTO is not related https://bugs.gentoo.org/buglist.cgi?quicksearch=fPIC&list_id=3710774

the only keepassxc-related bug i see is the submitter's with `-flto` enabled

**Comment by InBetweenNames** [comment] 2018-08-28 04:07
Can't reproduce:  `app-admin/keepassxc-2.3.4` installs here without a hitch, no override needed.

**Comment by InBetweenNames** [comment] 2018-08-28 04:08
Ahh sorry, just saw this.

**Comment by InBetweenNames** [comment] 2018-10-08 04:47
Fixed in `master`.  Conditional LTO based on `autotype` for this package has been added.

**Closed** 2018-10-08 04:47 UTC
