### ISSUE TITLE
x11-libs/gtk+-2.24.31-r1 fails to compile

### ISSUE THREAD

**Issue by flgw** [InBetweenNames/gentooLTO#41] opened 2017-10-13 16:54 UTC
Removing lto doesn't help here. Partial build.log:
```
In file included from /usr/include/pango-1.0/pango/pango.h:46:0,
                 from /var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31/gdk/gdktypes.h:37,
                 from /var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31/gdk/gdkscreen.h:32,
                 from /var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31/gdk/gdkapplaunchcontext.h:31,
                 from /var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31/gdk/gdk.h:32,
                 from /var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31/gtk/gtkstyle.h:35,
                 from /var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31/gtk/gtkrc.h:35,
                 from /var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31/gtk/queryimmodules.c:40:
/usr/include/pango-1.0/pango/pango-utils.h:32:10: note: declared here
 char **  pango_split_file_list (const char *str);
          ^
libtool: compile:  /usr/bin/gcc-5.4.0 -m32 -DHAVE_CONFIG_H -I. -I/var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31/gtk -I.. -DG_LOG_DOMAIN=\"Gtk\" -$
/var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31/gtk/gtkmountoperation-x11.c: In function ‘find_largest_sizes’:
/var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31/gtk/gtkmountoperation-x11.c:196:16: warning: variable ‘replace’ set but not used [-Wunused-but-set$
       gboolean replace;
                ^
/bin/sh ../libtool  --tag=CC   --mode=link /usr/bin/gcc-5.4.0 -m32  -O2 -pipe -march=native -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=both -Wall -version-info $
libtool: link: /usr/x86_64-pc-linux-gnu/gcc-bin/5.4.0/gcc-nm  .libs/gtkquery.o .libs/gtksearchengine.o .libs/gtksearchenginesimple.o .libs/fnmatch.o .libs/gtk$
libtool: link: /bin/grep -E -e "^[^_].*" ".libs/libgtk-x11-2.0.exp" > ".libs/libgtk-x11-2.0.expT"
libtool: link: mv -f ".libs/libgtk-x11-2.0.expT" ".libs/libgtk-x11-2.0.exp"
libtool: link: echo "{ global:" > .libs/libgtk-x11-2.0.ver
libtool: link:  cat .libs/libgtk-x11-2.0.exp | sed -e "s/\(.*\)/\1;/" >> .libs/libgtk-x11-2.0.ver
libtool: link:  echo "local: *; };" >> .libs/libgtk-x11-2.0.ver
libtool: link:  /usr/bin/gcc-5.4.0 -m32 -shared  -fPIC -DPIC  .libs/gtkquery.o .libs/gtksearchengine.o .libs/gtksearchenginesimple.o .libs/fnmatch.o .libs/gtk$
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: .libs/gtkmarshalers.o: multiple definition of 'g_cclosure_marshal_VOID__$
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/gtkmarshal.o: previous definition here
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: .libs/gtkmarshalers.o: multiple definition of 'g_cclosure_marshal_VOID__$
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/gtkmarshal.o: previous definition here
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: .libs/gtkmarshalers.o: multiple definition of 'g_cclosure_marshal_VOID__$
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/gtkmarshal.o: previous definition here
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: .libs/gtkmarshalers.o: multiple definition of 'g_cclosure_marshal_VOID(i$
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/gtkmarshal.o: previous definition here
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: .libs/gtkmarshalers.o: multiple definition of 'g_cclosure_marshal_VOID__$
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/gtkmarshal.o: previous definition here
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: .libs/gtkmarshalers.o: multiple definition of 'g_cclosure_marshal_VOID__$
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/gtkmarshal.o: previous definition here
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: .libs/gtkmarshalers.o: multiple definition of 'g_cclosure_marshal_VOID__$
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/gtkmarshal.o: previous definition here
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: error: .libs/gtkmarshalers.o: multiple definition of 'g_cclosure_marshal_VOID(i$
/usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/../../../../x86_64-pc-linux-gnu/bin/ld: .libs/gtkmarshal.o: previous definition here
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:2426: libgtk-x11-2.0.la] Error 1
make[4]: Leaving directory '/var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31-abi_x86_32.x86/gtk'
make[3]: *** [Makefile:5081: all-recursive] Error 1
make[3]: Leaving directory '/var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31-abi_x86_32.x86/gtk'
make[2]: *** [Makefile:2340: all] Error 2
make[2]: Leaving directory '/var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31-abi_x86_32.x86/gtk'
make[1]: *** [Makefile:733: all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/portage/x11-libs/gtk+-2.24.31-r1/work/gtk+-2.24.31-abi_x86_32.x86'
make: *** [Makefile:625: all] Error 2
 * ERROR: x11-libs/gtk+-2.24.31-r1::gentoo failed (compile phase):
 *   emake failed
```

**Comment by pchome** [comment] 2017-10-13 17:07
I re-emerged everything from x11-\*/\* not yet built w/ LTO tonight w/o any problems.
GCC 7.2.0

And yes, gtk+:2 seems to be one more package which strips unwanted flags
```
-m32  -O2 -pipe -march=native -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=both -Wall -version-info $
```

**Comment by InBetweenNames** [comment] 2017-10-13 19:47
I'll leave this issue open for now, but I can't reproduce this problem.

**Comment by flgw** [comment] 2017-10-13 21:56
Complete build log:
[build.log](https://github.com/InBetweenNames/gentooLTO/files/1384107/build.log)

**Comment by pchome** [comment] 2017-10-13 23:45
I even modified ebuild to be able compile it w/ LTO+O3+GRAPHITE and faced no problems.
I can't reproduce this too.

BTW: https://bugs.gentoo.org/133469 - 10+ y.o. bug and now 4 years since successful  build w/ -O3 reported. I quick-checked my gtk+:2 apps and can confirm no problems so far. So you comrades can test this too and report to upstream if everything is ok.

**Comment by InBetweenNames** [comment] 2017-10-14 15:02
Indeed, it looks like all LTO related flags are stripped from gtk+:2 when building it.  The multiple definition error must therefore be caused by something else.

@flgw , do you have any special linker things going on?  I notice you're using 32 bit from your build log.  Does the problem go away if you switch to the `ld.gold` to the `ld.bfd` linker, or vice versa?

**Comment by InBetweenNames** [comment] 2018-05-03 18:42
Tested again with GCC 8.1.0, no issues. As I have not heard about this problem from anyone else and we have failed to reproduce the problem, I'm going to close this issue. However, if anyone starts having problems again, I'll reopen it.

**Closed by InBetweenNames** 2018-05-03 18:42 UTC
