### ISSUE TITLE
Pcsx2 And LTO

### ISSUE THREAD

**Issue by javashin** [InBetweenNames/gentooLTO#339] opened 2019-06-02 04:38 UTC
https://gist.github.com/javashin/57129c8d704063fa620fa5f8d91bef29
pcsx2 compiles fine with only -O3 -march=native with new sys-devel/gcc-9.1.0-r1::gentoo
but not with lto

**Comment by ionenwks** [comment] 2019-06-02 05:01
Can confirm, builds fine with gcc 8.3.0 but not 9.1 when using LTO.

**Comment by arcum42** [comment] 2019-06-02 06:12
That certainly looks like *exactly* what it would do if you didn't have this gcc patch applied on gcc 9:
https://gitweb.gentoo.org/proj/gcc-patches.git/commit/?id=275ab714637a64672c6630cfd744af2c70957d5a

Down to which file it crashes on.

**Comment by ionenwks** [comment] 2019-06-02 06:58
Looking at my last gcc build log, I see the the `*   26_all_ipa-incomplete.patch ...` though, so the patch should be on, I don't have multiple versions of gcc 9 installed either.

**Comment by ionenwks** [comment] 2019-06-02 07:09
But looking at the patch itself, I don't really know anything about gcc's inner working but that `!in_lto_p` that was there both before and after gives me the impression it changes nothing at all if LTO is enabled.

**Comment by InBetweenNames** [comment] 2019-06-27 04:05
Closing issue as we now use `ld.bfd` as default (associated patch was merged).

**Closed by InBetweenNames** 2019-06-27 04:05 UTC

**Comment by javashin** [comment] 2019-06-27 05:59
ok but forcing ld.bfd does make compile pcsx2 with gcc 9.1 and with lto last time i tried never work and for me pcsx2 builds fine with -O3 -march=native + ld.gold

**Comment by javashin** [comment] 2019-08-14 02:13
/var/tmp/portage/games-emulation/pcsx2-9999/work/pcsx2-9999/plugins/GSdx/PSX/GPUDrawScanline.cpp:78:1: internal compiler error: Segmentation fault


ICE with lto ld.bfd as default and new gcc 9.2.0

**Comment by javashin** [comment] 2019-08-14 02:14
using only -march-native -O3 -flto=3 -fuse-linker-plugin

**Comment by javashin** [comment] 2019-08-14 02:15
ICEICEICE

**Comment by ionenwks** [comment] 2019-08-14 06:16
Wait, why was this closed on the linker change commit? I'm pretty sure this whole thing doesn't have anything to do with the linker, it's a gcc bug. There was a patch on gentoo's side to fix it but I don't think it's working as intended. 

Didn't try myself but unfortunate to hear it still fails with 9.2, looking at the comments on the PCSX2 git, it seems like they were hoping for 9.2 to fix it, guess the patches didn't make it in:
https://github.com/PCSX2/pcsx2/commit/43981f5981b0c5578af2243b3db26f0cdb1a1bbd
