### ISSUE TITLE
media-libs/x264-0.0.20190903-r1 fails to patch

### ISSUE THREAD

**Issue by Althorion** [InBetweenNames/gentooLTO#543] opened 2020-06-29 12:16 UTC
```
 * Package:    media-libs/x264-0.0.20190903-r1
 * Repository: gentoo
 * Maintainer: media-video@gentoo.org
 * USE:        abi_x86_64 amd64 cpu_flags_x86_sse elibc_glibc interlaced kernel_linux threads userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
 * FEATURES='assume-digests binpkg-docompress binpkg-dostrip binpkg-logs candy cgroup config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandboxmerge-sync multilib-strict network-sandbox news parallel-fetch parallel-install pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr'
 * CFLAGS='-O3 -march=native -pipe -Wl,-O1 -Wl,--as-needed'
 * CXXFLAGS='-O3 -march=native -pipe -Wl,-O1 -Wl,--as-needed'
 * FFLAGS='-O3 -march=native -pipe -Wl,-O1 -Wl,--as-needed'
 * FCFLAGS='-O3 -march=native -pipe -Wl,-O1 -Wl,--as-needed'
 * F77FLAGS='-O3 -march=native -pipe -Wl,-O1 -Wl,--as-needed'
 * LDFLAGS='-Wl,-O1 -Wl,--as-needed'
 * MAKEOPTS='-j32'
 * gcc (Gentoo 10.1.0-r1 p2) 10.1.0
 * g++ (Gentoo 10.1.0-r1 p2) 10.1.0
 * GNU ld (Gentoo 2.33.1 p2) 2.33.1
 * Linux ripper 5.7.6 #1 SMP PREEMPT Thu Jun 25 18:55:31 -00 2020 x86_64 AMD Ryzen Threadripper 1950X 16-Core Processor AuthenticAMD GNU/Linux
media-libs/x264: 34 seconds average for 1 merge
2020-06-27T15:39:43 >>> media-libs/x264: 34 seconds
ESC]0;emerge 14:12:01 210|523 x264 00:34 (root@ripper)^G>>> Unpacking source...
>>> Unpacking x264-snapshot-20190903-2245.tar.bz2 to /var/tmp/portage/media-libs/x264-0.0.20190903-r1/work
>>> Source unpacked in /var/tmp/portage/media-libs/x264-0.0.20190903-r1/work
 * Applying lto.patch ...
 [ ok ]
 * lto-overlay: LTO patches applied.
>>> Preparing source in /var/tmp/portage/media-libs/x264-0.0.20190903-r1/work/x264-snapshot-20190903-2245 ...
 * Applying x264-0.0.20190903-STRINGS.patch ...
patching file configure
Hunk #1 succeeded at 532 (offset -9 lines).
Hunk #2 FAILED at 1018.
1 out of 2 hunks FAILED -- saving rejects to file configure.rej
 [ !! ]
 * ERROR: media-libs/x264-0.0.20190903-r1::gentoo failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/media-libs/x264-0.0.20190903-r1/files/x264-0.0.20190903-STRINGS.patch
 *
 * Call stack:
 *               ebuild.sh, line  125:  Called src_prepare
 *             environment, line 3146:  Called default
 *      phase-functions.sh, line  855:  Called default_src_prepare
 *      phase-functions.sh, line  920:  Called __eapi6_src_prepare
 *             environment, line 1355:  Called eapply '/var/tmp/portage/media-libs/x264-0.0.20190903-r1/files/x264-0.0.20190903-STRINGS.patch'
 *             environment, line 1764:  Called _eapply_patch '/var/tmp/portage/media-libs/x264-0.0.20190903-r1/files/x264-0.0.20190903-STRINGS.patch'
 *             environment, line 1702:  Called __helpers_die 'patch -p1  failed with /var/tmp/portage/media-libs/x264-0.0.20190903-r1/files/x264-0.0.20190903-STRINGS.patch'
 *   isolated-functions.sh, line  112:  Called die
 * The specific snippet of code:
 *              die "$@"
 *
 * If you need support, post the output of `emerge --info '=media-libs/x264-0.0.20190903-r1::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=media-libs/x264-0.0.20190903-r1::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/media-libs/x264-0.0.20190903-r1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-libs/x264-0.0.20190903-r1/temp/environment'.
 * Working directory: '/var/tmp/portage/media-libs/x264-0.0.20190903-r1/work/x264-snapshot-20190903-2245'
 * S: '/var/tmp/portage/media-libs/x264-0.0.20190903-r1/work/x264-snapshot-20190903-2245'
```

**Comment by ElDavoo** [comment] 2020-06-29 13:00
Duplicate of #538

**Closed** 2020-06-29 13:01 UTC
